### PR TITLE
Fix issue #42

### LINKED ISSUE #42: Saving a layered_image doesn't overwrite an old one with the same name
It just adds extra layers without a warning in a jupyter notebook.

### PR DESCRIPTION
**Pull request by jeremykubica**
Fix issue #42 by making the saveLayers function overwrite existing files.

Add a test to confirm functionality.

Closes #42

### CODE REVIEW

File: search/src/LayeredImage.cpp [hunk 1]
```diff
@@ -189,19 +189,37 @@ void LayeredImage::subtractTemplate(const RawImage& subTemplate)
...
+    // If we are unable to create the file, check if it already exists
+    // and, if so, delete it and retry the create.
+    if (status == 105)
+    {
+        status = 0;
+        fits_open_file(&fptr, (path+fileName+".fits").c_str(),
+                       READWRITE, &status);
+        if (status == 0)
+        {
+            printf("Fits file '%s' already exists. Deleting.\n",
```
Comment (PWhiddy) [inline search/src/LayeredImage.cpp:206]: Not an issue but just noting, stdout / stderr won't show up in a jupyter notebook, only through the console.

Comment (PWhiddy) [inline search/src/LayeredImage.cpp:206]: Not an issue but just noting, stdout / stderr won't show up in a jupyter notebook, only through the console.

**Review by PWhiddy — APPROVED** [review]
Looks good to me, thanks!
